config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :articles 


  get '/categories/new'
 	post '/categories/new'

	root 'articles#index'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user, optional: true
	belongs_to :category, optional: true
	#belongs_to :username, optional: true
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :articles
	has_many :users
	accepts_nested_attributes_for :articles   #fix error????
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	#before_action :set_article, only: [:index]

	
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :current_user_present, only: [:index, :show]

  def index   
    if params[:category].blank?
      @articles = Article.all        
    else
      @category_id = Category.find_by(name: params[:category]).id
      @articles = Article.where(category_id: @category_id)
    end

      @articles_number = @articles.count
  end

  def show     
           
  end

  def new
    @article = Article.new
    @current_user_email = current_user.email

  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :body, :image_url, :category_id)
    end

    def current_user_present
    if current_user.present?
      @current_user_email = current_user.email
      @current_user_username = current_user.username
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	#before_action :set_category, only: [:show, :edit, :update, :destroy]

	def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to root_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    

    def category_params
      params.require(:category).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">    
    <%= form.text_field :title, class: 'form-control', placeholder: 'Title of Article' %>
  </div>

  <div class="form-group">    
    <%= form.text_area :body, class: 'form-control', placeholder: 'Article Body' %>
  </div>

  <div class="form-group">    
    <%= form.text_field :image_url, class: 'form-control', placeholder: 'Image URL' %>
  </div>
  <div class="c-select">
    <%= form.collection_select :category_id, Category.all, :id, :name, {prompt: 'Choose a Category'}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit 'Submit', class: 'btn btn-default btn-primary' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= image_tag @article.image_url, align: 'center' %>


<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<% if request.original_url.split('=').last.include? '/' %>
  <h1>All Articles (<%= @articles_number %>) </h1>
  <br>
<% else %>
  <h1>All <%= request.original_url.split('=').last.pluralize %> (<%= @articles_number %>)</h1>
  <br>
<% end %>

 
<% @articles.each do |article| %>
	<h4>
		<%= image_tag(article.image_url, width: 50, height: 50) %>
		<%= link_to article.title, article %>
	</h4>
  
  <p>
  	<%= truncate(article.body, length: 200) %>
  </p>
<% end %>



     

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<style media="screen">
	img {
		max-width: 200px;
		max-height: 200px;
	}
</style>

<p id="notice"><%= notice %></p>

<h1>
	<%= @article.title %>		
</h1>  

<p>	
  <%= image_tag @article.image_url, align: 'right' %>
  <%= @article.body %>
	<br>
	<br>
  Article by:  <%= @article_author_username %>
  <br>
  <br>
  <%= @article.image_url %>
</p>

<% if user_signed_in? %>
	<%= link_to 'Edit', edit_article_path(@article), class: "btn btn-danger btn-sm" %>	
<% end %>

<%= link_to 'Back', articles_path, class: "btn btn-primary btn-sm" %>

app/views/categories/_form.html.erb
<%= form_with(url: categories_new_path,local: true) do |form| %>
  

  <div class="form-group">    
    <%= form.text_field :category_name, class: 'form-control', placeholder: 'Create New Category' %>
  </div>

  
  <div class="form-group">
    <%= form.submit 'Submit', class: 'btn btn-default btn-primary' %>
  </div>
<% end %>

app/views/categories/new.html.erb
<h1>Create New Category</h1>

<%= render 'form', form: @category %>

<%= link_to 'Back', root_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" ><img src="/assets/logo.png"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">  
    <ul class="navbar-nav">
    <% if user_signed_in? %>
        <li class="nav-item active">      
        <a class="nav-link" href="#"><%= link_to "New Article", new_article_path %><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">User:  <%= @current_user_email %></a>
      </li>
  <% else %>
      <li class="nav-item">
        <a class="nav-link" href="#"><%= link_to "Login", new_user_session_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" ><%= link_to "Signup", new_user_registration_path %></a>
      </li>
 <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="container">
    <div class="row">
      <div class="col-lg-9">
        <%= yield %>
      </div>
    <div class="col-lg-3">
      <ul class="nav-pills nav-stacked">
        <li><%= link_to "All Categories", root_path %></li>
        <% Category.all.each do |category| %>
          <li><%= link_to category.name, articles_path(category: category.name) %></li>          
        <% end %>

        <% if user_signed_in? %>
          <li><%= link_to "New Category", categories_new_path %></li>
        <% end %>
      </ul>
    </div>     
  </div>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wiki219</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= render 'layouts/sidebar' %>

  </body>
</html>